### ISSUE TITLE
Beard and Laravel Spark?

### ISSUE THREAD

**Issue by calebporzio** [monarkee/beard#17]
Hey David,

I've been using beard to build the marketing page for new project built on Laravel Spark. Essentially here are the problems I'm coming across (sorry if this is not the right place).

You should be able to check out what I have so far here:
[https://output.jsbin.com/qofagomexi](https://output.jsbin.com/qofagomexi)

I went from never using Beard to building something (barebones) that suites me well in probably 2 hours or so. I am loving this project. I am doing things with it bootstrap simply is not capable of and I am usually too intimidated to style things like this by hand.

I will just list my thought progression in bullet format and hopefully you can give me some guidance. I know I'm asking a lot, but I think other adopters coming from the standard: Laravel / Vuejs / Bootstrap background would probably experience the same things.

- I build the marketing page in Beard and LOVED IT.
- Spark / Bootstrap use LESS, so I needed to make a completely separate layout and stylesheet that is built from a sass file
- Now I want the rest of the app (built on bootstrap) to look the same
- I weigh my options
  - try to manually mirror the look of the marketing page with custom css 
    - this would feel hacky and I wouldn't be able to use Beard throughout the app.
  - somehow tac Beard onto bootstrap to use the colors and fonts, and helpers and such, but still have access to form controls and the grid and such.
  - scrap all Spark's styling / classes and build it with Beard
    - this excites me
    - then I realize Beard doesn't have everything I need: form inputs, panels, buttons, etc...
    - then I remember you mentioned that on the "Philosophy" page
    - I go to the Philosophy page and am confused weather you're suggesting I copy the same css classes for each button, or make custom helpers. Also, you mention: "build your own framework using Beard" - I definitely want to do that and am willing to put in the time, I think I would just need more guidance as to what that would look like.

Sorry for the mouthful. I will be launching the app in the near future and would love to entirely use Beard for it, I think I just need some help.

Thanks,
Caleb

**Comment by davidhemphill** [comment]
I'm glad you are liking Beard! Thank you for giving it a shot on a project. Also, thank you for the issues and PR's you've been creating.

Integrating Beard with a framework like Bootstrap will be a tall order. Those frameworks come with a huge bag of opinions and conventions, and it'd be really hard to keep all of that in sync. Not to mention the file size could be gargantuan...and that's no good for anyone.

Beard is really best suited as the foundation for creating your own framework. In projects that I work on, I use only Beard helpers as much as I can...until I'm forced to create a project-specific helper (think height declarations or absolute positioned elements specific to one page) or convenience styles (for markdown output or tables). This provides me a level of consistency throughout an entire project which helps reduce the number of styling options I have when building things out...which I like.

Once you starting collecting the various helper classes into "higher-order" classes, I think we start backtracking on what makes the atomic approach so great. However, I understand a lot of folks want a full framework with a set of components, and so I may build something out like that one day from the various projects that use it.

**Comment by calebporzio** [comment]
Great,

Really appreciate the reply. I've been ripping out Spark's bootstrap which is quite the task but hopefully well worth it.

Also, I've been referencing push silver for lots of things and to get an idea about how you approach a project.

I think it would be very helpful to have an "examples", "built with beard" or "showcase" page in the docs as well.

Thanks again
