### ISSUE TITLE
what about giving an element less than 1rem size?

### ISSUE THREAD

**Issue by miranrasuli** [monarkee/beard#21]
Hi!
Thankfully we have the Spacing system so we can use margins and paddings. 
But want if we want to give an element less than 1rem (e.g, 0.5rem) ?
giving `pv0.5` doesn't work.

**Comment by davidhemphill** [comment]
I think you'll like #22 :-)

Basically v2.1.0 adds the ability to do this:

```scss
@include new-spacing-helper('0-5', 0.5);
```

which will output responsive spacing helpers like this:

```css
.pt0-5 {
     padding-top: 0.5rem !important;
}
```
